import { describe, it, expect } from 'vitest'
import {
    CANONICAL_ORIGIN, DESCRIPTION, GROUND, NAME, SHORT_DESCRIPTION, TITLE, resolveSiteUrl,
} from '@/app/siteMetadata'
import manifest from '@/app/manifest'

/**
 * Where an absolute URL in a meta tag points when nobody has configured anything
 * (spec P2-2, row 20f).
 *
 * This is the case that cannot be tested in the browser suite, because the harness
 * *always* configures it: `e2e/server.ts` builds with `NEXT_PUBLIC_SITE_URL` set to the
 * test server's origin so a missing `metadataBase` is observable at all. The deployed
 * build is the one with nothing set, and until this row it resolved to
 * `http://localhost:3000` — absolute, valid, and pointing at whoever opened the link.
 */

describe('the site URL', () => {
    it('is the canonical deployment when nothing is configured', () => {
        // The defect this row fixes. Naming localhost explicitly is worse than leaving
        // `metadataBase` unset, because Next's own default consults `VERCEL_URL` first;
        // supplying a value suppresses that and pins every deployment to a laptop.
        expect(resolveSiteUrl(undefined)).toBe(CANONICAL_ORIGIN)
        expect(resolveSiteUrl(undefined)).not.toMatch(/localhost|127\.0\.0\.1/)
        expect(CANONICAL_ORIGIN).toBe('https://domino-fill.vercel.app')
    })

    it('treats an empty or blank variable as unset', () => {
        // A deploy platform that defines the variable without a value is the ordinary way
        // this arrives, and `?? fallback` does not catch it.
        for (const blank of ['', '   ', '\n']) {
            expect(resolveSiteUrl(blank), JSON.stringify(blank)).toBe(CANONICAL_ORIGIN)
        }
    })

    it('uses the override when there is one, which is what the harness depends on', () => {
        expect(resolveSiteUrl('http://127.0.0.1:3100')).toBe('http://127.0.0.1:3100')
        expect(resolveSiteUrl('https://staging.example.com')).toBe('https://staging.example.com')
        // Trimmed and reduced to an origin, so a trailing path or a stray newline in a CI
        // variable cannot end up inside every OG URL.
        expect(resolveSiteUrl(' https://example.com/game/ ')).toBe('https://example.com')
    })

    it('trims whitespace the URL parser does not', () => {
        /*
         * Why the `.trim()` is load-bearing rather than decorative -- found by mutation,
         * which is also how the limits of it were measured. The WHATWG URL parser strips
         * leading and trailing *ASCII* whitespace itself, so removing the trim is invisible
         * for spaces and newlines. It does not strip the rest of Unicode's whitespace, and
         * a URL pasted out of a rendered page or a chat app into a deploy variable can
         * carry a non-breaking space. Without the trim that value throws and the site
         * quietly falls back.
         */
        expect(resolveSiteUrl(' https://staging.example.com '))
            .toBe('https://staging.example.com')
        expect(resolveSiteUrl('　https://staging.example.com'))
            .toBe('https://staging.example.com')
    })

    it('falls back rather than throwing on a malformed value', () => {
        /*
         * `new URL()` throwing inside `metadata` fails the build. A typo in a deploy
         * variable is not worth taking a site down for when a correct answer is available
         * -- and a non-HTTP scheme would produce meta tags no crawler can follow.
         */
        for (const bad of ['not a url', 'https://', 'mailto:hi@example.com', 'file:///tmp']) {
            expect(resolveSiteUrl(bad), bad).toBe(CANONICAL_ORIGIN)
        }
    })
})

describe('the strings the page and the manifest share', () => {
    /*
     * Row 20b said a manifest *route* stops these drifting "without TypeScript noticing".
     * It does not: two identical string literals in two files are not a type error. What
     * actually stops it is reading from one module, and this is the check that they do.
     * The served-vs-served version is in `e2e/metadata.spec.ts`.
     */
    it('come from one module', () => {
        const served = manifest()
        expect(served.name).toBe(NAME)
        expect(served.short_name).toBe(NAME)
        expect(served.description).toBe(SHORT_DESCRIPTION)
        expect(served.theme_color).toBe(GROUND)
        expect(served.background_color).toBe(GROUND)
    })

    it('are the game, not the scaffold it started from', () => {
        for (const text of [NAME, TITLE, DESCRIPTION, SHORT_DESCRIPTION]) {
            expect(text).not.toMatch(/create next app|generated by/i)
        }
        expect(TITLE).toContain(NAME)
        // The long one is for a search result; the short one has to fit a preview card.
        expect(DESCRIPTION.length).toBeGreaterThan(SHORT_DESCRIPTION.length)
    })
})
