import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreWrapper } from "./provider";
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * `viewportFit: 'cover'` is what makes `env(safe-area-inset-*)` report anything but zero:
 * without it the page is laid out inside the safe area already and the insets are 0, so
 * the notch simply eats the board's width with nothing able to see it.
 *
 * Zoom is left enabled on purpose. Banning it is the usual "fix" for layout that does not
 * survive scaling, and it takes pinch-zoom away from the people who need it most.
 */
export const viewport: Viewport = {
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Inside <body>, not wrapping <html>: the provider is a client component, and
            handing it the document element pulls the whole store graph into every route's
            SSR module graph and makes <head> hoisting/streaming fragile. */}
        <StoreWrapper>
          {children}
        </StoreWrapper>
        <SpeedInsights />
      </body>
    </html>
  );
}
