import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreWrapper } from "./provider";
import { SpeedInsights } from "@vercel/speed-insights/next"
import {
  DESCRIPTION, GROUND, ICON_512, NAME, SHORT_DESCRIPTION, TITLE, resolveSiteUrl,
} from "./siteMetadata";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * What the game is called, everywhere it is named (spec P2-2, row 20b).
 *
 * This said "Create Next App" / "Generated by create next app" until row 20b, which is the
 * title in the browser tab, the name a bookmark takes, the heading a shared link shows in
 * a chat app, and the text a search engine indexes. For a game whose whole retention model
 * is "come back tomorrow", being unnamed in every one of those places is not cosmetic.
 *
 * `metadataBase` is what makes the OG image URL absolute, which is required: relative URLs
 * in Open Graph tags are not resolved by most crawlers, so the preview silently falls back
 * to no image at all. Where that base comes from — and why it must not be localhost — is
 * `siteMetadata.ts`, along with the strings this shares with the manifest.
 */
const siteUrl = resolveSiteUrl(process.env.NEXT_PUBLIC_SITE_URL)

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: NAME,
  appleWebApp: {
    // iOS reads this instead of the manifest, and the short name is what fits under an
    // icon on a home screen.
    capable: true,
    title: NAME,
    statusBarStyle: 'default',
  },
  openGraph: {
    type: 'website',
    siteName: NAME,
    title: TITLE,
    description: SHORT_DESCRIPTION,
    url: '/',
    images: [{ url: ICON_512, width: 512, height: 512, alt: 'A domino' }],
  },
  twitter: {
    card: 'summary',
    title: TITLE,
    description: SHORT_DESCRIPTION,
    images: [ICON_512],
  },
};

/**
 * `viewportFit: 'cover'` is what makes `env(safe-area-inset-*)` report anything but zero:
 * without it the page is laid out inside the safe area already and the insets are 0, so
 * the notch simply eats the board's width with nothing able to see it.
 *
 * Zoom is left enabled on purpose, and `userScalable` is left *unset* rather than set to
 * true: the default is already enabled, and an explicit `true` invites someone to flip it.
 * Banning zoom is the usual "fix" for layout that does not survive scaling -- the layout
 * suite proves this one does, at 50% through 200% -- and it takes pinch-zoom away from the
 * people who need it most.
 *
 * `themeColor` matches the board's ground so the browser's own chrome does not sit as a
 * bright white band above a grey page on a phone.
 */
export const viewport: Viewport = {
  viewportFit: 'cover',
  themeColor: GROUND,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Inside <body>, not wrapping <html>: the provider is a client component, and
            handing it the document element pulls the whole store graph into every route's
            SSR module graph and makes <head> hoisting/streaming fragile. */}
        <StoreWrapper>
          {children}
        </StoreWrapper>
        <SpeedInsights />
      </body>
    </html>
  );
}
