import { test, expect } from '@playwright/test'

/**
 * What the served page actually says it is (spec P2-2, row 20b).
 *
 * A browser test because every one of these is produced by the framework from a config
 * object, and the question is whether the tag reached the document -- the same distinction
 * row 19 was about. A unit test of the `metadata` export would only re-read the literal
 * that was written.
 *
 * Against the production build, so it also covers the manifest and icon *routes* resolving
 * rather than 404ing, which is the failure mode that makes an install prompt silently never
 * appear.
 */

test('the page is named, in the tab and to a crawler', async ({ page }) => {
    await page.goto('/')

    // "Create Next App" until row 20b: the browser tab, the bookmark, the link preview and
    // the search result all said it.
    await expect(page).toHaveTitle(/Domino Fill/)
    expect(await page.title()).not.toMatch(/create next app/i)

    const description = page.locator('meta[name="description"]')
    await expect(description).toHaveAttribute('content', /domino/i)
    await expect(description).not.toHaveAttribute('content', /generated by/i)
})

test('a shared link previews as the game', async ({ page }) => {
    await page.goto('/')

    await expect(page.locator('meta[property="og:title"]'))
        .toHaveAttribute('content', /Domino Fill/)
    await expect(page.locator('meta[property="og:type"]')).toHaveAttribute('content', 'website')

    /*
     * Absolute, which is the part worth testing. Relative URLs in Open Graph tags are not
     * resolved by most crawlers, so a relative image is the same as no image -- and it
     * fails invisibly, because the page itself renders perfectly.
     */
    const image = await page.locator('meta[property="og:image"]').getAttribute('content')
    expect(image).toMatch(/^https?:\/\//)
    expect(image).toMatch(/icon-512\.png$/)

    /*
     * And built from the *configured* site URL, not from Next's fallback. With
     * `metadataBase` unset Next uses `http://localhost:3000` and only warns at build time,
     * so a deployed page advertises a preview image on somebody's laptop -- valid,
     * absolute, and wrong. The harness builds with `NEXT_PUBLIC_SITE_URL` set to the test
     * server's own origin so the two are distinguishable at all; without that, a mutation
     * deleting `metadataBase` is invisible.
     */
    expect(new URL(image!).origin).toBe(new URL(page.url()).origin)
})

test('the manifest is served, and names icons that exist', async ({ page, request }) => {
    await page.goto('/')
    await expect(page.locator('link[rel="manifest"]')).toHaveCount(1)

    const href = await page.locator('link[rel="manifest"]').getAttribute('href')
    const manifest = await request.get(new URL(href!, page.url()).toString())
    expect(manifest.status()).toBe(200)

    const parsed = await manifest.json()
    expect(parsed.name).toBe('Domino Fill')
    expect(parsed.start_url).toBe('/')
    expect(parsed.display).toBe('standalone')
    expect(parsed.icons.length).toBeGreaterThan(0)

    // The failure this test exists for: a manifest is valid JSON whether or not its icons
    // resolve, and Chrome simply declines to offer installation with no error anywhere.
    for (const icon of parsed.icons as { src: string }[]) {
        const response = await request.get(new URL(icon.src, page.url()).toString())
        expect(response.status(), `${icon.src} is missing`).toBe(200)
        expect(response.headers()['content-type']).toContain('image/png')
    }

    // Android crops a maskable icon to the launcher's shape; without one declared it gets
    // a white box with the icon shrunk inside it.
    expect((parsed.icons as { purpose?: string }[]).some(i => i.purpose === 'maskable')).toBe(true)
})

test('iOS gets an icon it will actually use', async ({ page, request }) => {
    // Safari ignores the manifest for home-screen icons and reads this link instead.
    await page.goto('/')
    const apple = page.locator('link[rel="apple-touch-icon"]')
    await expect(apple).toHaveCount(1)

    const href = await apple.getAttribute('href')
    const response = await request.get(new URL(href!, page.url()).toString())
    expect(response.status()).toBe(200)
    expect(response.headers()['content-type']).toContain('image/png')
})

test('zoom is still allowed', async ({ page }) => {
    /*
     * The spec is explicit that `userScalable` stays enabled: banning zoom is the usual
     * "fix" for a layout that does not survive scaling, and it takes pinch-zoom from the
     * people who need it most. The layout suite proves this one survives 50%-200%, so
     * there is nothing to "fix".
     *
     * Asserted as the absence of the ban rather than the presence of a permission, because
     * that is the actual contract -- scalable is the default.
     */
    await page.goto('/')
    const viewport = await page.locator('meta[name="viewport"]').getAttribute('content')
    expect(viewport).not.toMatch(/user-scalable\s*=\s*(no|0)/i)
    expect(viewport).not.toMatch(/maximum-scale\s*=\s*1(\.0)?\b/i)
    // And the part that makes the safe-area insets non-zero at all (P0-3).
    expect(viewport).toMatch(/viewport-fit\s*=\s*cover/i)
})
