import { CONTROL, control, type Variant, type VariantName } from '../app/controls'
import { cssName, type Token } from '../app/palette'

/**
 * `app/controls.css`, rendered from `app/controls.ts` (graphics spec P2-2, row 14).
 *
 * The pattern `palette-css.ts` set: CSS cannot import TypeScript, so the stylesheet's half is
 * generated, committed, and required byte-identical to this by `tests/controls.test.ts`.
 *
 * One rule set per variant, in the `components` layer: above the base layer's rules for
 * every button (P1-6's focus and press, P2-1's text), and below Tailwind's utilities, so
 * `aria-pressed`, which `controlStates.ts` draws with utilities, wins over the variant's rest.
 * The archive's current day is the `day` variant's own (`aria-current`, below). Hover waits
 * for a fine pointer that can hover, as every hover in the game must (P1-6).
 */
export const CONTROLS_CSS_PATH = 'app/controls.css'

const v = (token: Token) => `var(--${cssName(token)})`

const rules = (name: VariantName): string[] => {
    const c: Variant = CONTROL[name]
    const at = `.${control(name)}`
    const edge = c.edge?.width ?? 0
    const rest = [
        typeof c.surface === 'string' ? `background-color: ${v(c.surface)};` : null,
        c.edge ? `border: ${c.edge.width}px solid ${v(c.edge.colour)};` : null,
        `border-radius: ${c.radius}px;`,
        `padding: ${c.padding.y - edge}px ${c.padding.x - edge}px;`,
        c.ink ? `color: ${v(c.ink)};` : null,
        `font-weight: ${c.weight};`,
    ]
    const block = (selector: string, lines: (string | null)[], indent = '  ') => {
        const body = lines.filter((l): l is string => l !== null)
        return body.length === 0 ? [] : [`${indent}${selector} {`, ...body.map(l => `${indent}  ${l}`), `${indent}}`]
    }
    const marks = c.surface !== null && typeof c.surface === 'object'
        ? Object.entries(c.surface).flatMap(([mark, token]) =>
            block(`${at}[data-mark="${mark}"]`, [`background-color: ${v(token)};`]))
        : []
    const hover = block(`${at}:enabled:hover`, [
        c.hover.surface ? `background-color: ${v(c.hover.surface)};` : null,
        c.hover.ring ? `box-shadow: 0 0 0 2px ${v(c.hover.ring)};` : null,
        c.hover.scale ? `scale: ${c.hover.scale};` : null,
    ], '    ')
    return [
        ...block(at, rest),
        ...marks,
        ...(c.current ? block(`${at}[aria-current]`, [`box-shadow: 0 0 0 2px ${v(c.current.ring)};`]) : []),
        ...block(`${at}:focus-visible`, [`outline-color: ${v(c.focus)};`]),
        ...block(`${at}:disabled`, [
            c.disabled.surface ? `background-color: ${v(c.disabled.surface)};` : null,
            c.disabled.opacity !== undefined ? `opacity: ${c.disabled.opacity};` : null,
            c.disabled.filter ? `filter: ${c.disabled.filter};` : null,
        ]),
        ...(hover.length ? ['  @media (hover: hover) and (pointer: fine) {', ...hover, '  }'] : []),
        // After the hover, which it ties on specificity: a pointer pressing is also hovering,
        // and the press is what it is doing.
        ...block(`${at}:not(:disabled):active`, [c.press.surface ? `background-color: ${v(c.press.surface)};` : null]),
    ]
}

export const renderControlsCss = (): string => [
    '/*',
    ' * Generated by `npm run tokens` from `app/controls.ts`. Do not edit: change the variant',
    ' * there and regenerate. `tests/controls.test.ts` fails when the two disagree.',
    ' */',
    '@layer components {',
    ...(Object.keys(CONTROL) as VariantName[]).flatMap(rules),
    '}',
    '',
].join('\n')
