import { PALETTE, cssName, type Token } from '../app/palette'

/**
 * `app/palette.css`, rendered from `app/palette.ts` (graphics spec P0-5, row 5).
 *
 * CSS cannot import TypeScript, so the stylesheet's half of the palette is generated and
 * committed -- the pattern rows 20b/20h used for the icons, and failing the same way:
 * `tests/palette.test.ts` requires the committed file to be byte-identical to this, so a
 * token edited without `npm run tokens` fails the suite instead of shipping two palettes.
 *
 * Two blocks. `:root` makes every token a custom property (`--tile-face`), for plain CSS and
 * inline styles. `@theme inline` hands each one to Tailwind as a colour (`bg-tile-face`,
 * `ring-focus-ring/50`), pointing at the property rather than copying the value, so there is
 * still exactly one place the value is written.
 */
export const PALETTE_CSS_PATH = 'app/palette.css'

export const renderPaletteCss = (): string => {
    const tokens = Object.keys(PALETTE) as Token[]
    return [
        '/*',
        ' * Generated by `npm run tokens` from `app/palette.ts`. Do not edit: change the token',
        ' * there and regenerate. `tests/palette.test.ts` fails when the two disagree.',
        ' */',
        ':root {',
        ...tokens.map(t => `  --${cssName(t)}: ${PALETTE[t]};`),
        '}',
        '',
        '@theme inline {',
        ...tokens.map(t => `  --color-${cssName(t)}: var(--${cssName(t)});`),
        '}',
        '',
    ].join('\n')
}
