import { TYPE, roleName, type Role } from '../app/typography'

/**
 * `app/typography.css`, rendered from `app/typography.ts` (graphics spec P2-1, row 13).
 *
 * The pattern `palette-css.ts` set: CSS cannot import TypeScript, so the stylesheet's half is
 * generated, committed, and required byte-identical to this by `tests/typography.test.ts`.
 *
 * One `@theme inline` block. `--text-*: initial` first, which drops Tailwind's whole default
 * size scale -- `text-xs` to `text-9xl` then generate nothing -- and then one `--text-<role>`
 * with its `--line-height` per role, which Tailwind turns into `text-<role>`, setting both.
 *
 * `inline` because of the board label. Its size is `var(--label-font)`, which each board sets
 * on its own shell; a theme variable declared on `:root` would resolve that reference *there*,
 * where no board has set it, and every label would lose its size. Inlined, the utility reads
 * `--label-font` on the label itself.
 */
export const TYPOGRAPHY_CSS_PATH = 'app/typography.css'

const size = (role: Role): string => {
    const s = TYPE[role].size
    return typeof s === 'number' ? `${s}px` : s
}

export const renderTypographyCss = (): string => {
    const roles = Object.keys(TYPE) as Role[]
    return [
        '/*',
        ' * Generated by `npm run tokens` from `app/typography.ts`. Do not edit: change the role',
        ' * there and regenerate. `tests/typography.test.ts` fails when the two disagree.',
        ' */',
        '@theme inline {',
        '  --text-*: initial;',
        ...roles.flatMap(r => [
            `  --text-${roleName(r)}: ${size(r)};`,
            `  --text-${roleName(r)}--line-height: ${TYPE[r].lineHeight};`,
        ]),
        '}',
        '',
    ].join('\n')
}
